#!/usr/bin/env bash
set -euo pipefail

fail() {
  echo "iOS Google Sign-In configuration error: $1" >&2
  exit 1
}

require_value() {
  local name="$1"
  local value="${!name:-}"
  [[ -n "${value//[[:space:]]/}" ]] || fail "$name must be set"
}

is_google_client_id() {
  [[ "$1" =~ ^[A-Za-z0-9._-]+\.apps\.googleusercontent\.com$ ]]
}

google_value_names=(
  GOOGLE_SIGN_IN_SERVER_CLIENT_ID
  GOOGLE_SIGN_IN_IOS_CLIENT_ID
  GOOGLE_SIGN_IN_IOS_REVERSED_CLIENT_ID
)
configured_google_values=0
for value_name in "${google_value_names[@]}"; do
  value="${!value_name:-}"
  [[ -n "${value//[[:space:]]/}" ]] && ((configured_google_values += 1))
done

# An Apple-only archive must not inherit a generated configuration from an
# earlier build. Google is either configured as one complete identity or off.
if [[ "$configured_google_values" -eq 0 ]]; then
  rm -f ios/Flutter/GoogleSignIn.xcconfig
  printf '%s\n' 'Google Sign-In is not configured; no native config generated.'
  exit 0
fi

for value_name in "${google_value_names[@]}"; do
  require_value "$value_name"
done

is_google_client_id "$GOOGLE_SIGN_IN_SERVER_CLIENT_ID" || fail "GOOGLE_SIGN_IN_SERVER_CLIENT_ID must be a Google OAuth client ID"
is_google_client_id "$GOOGLE_SIGN_IN_IOS_CLIENT_ID" || fail "GOOGLE_SIGN_IN_IOS_CLIENT_ID must be a Google OAuth client ID"

expected_reversed_client_id="com.googleusercontent.apps.${GOOGLE_SIGN_IN_IOS_CLIENT_ID%.apps.googleusercontent.com}"
[[ "$GOOGLE_SIGN_IN_IOS_REVERSED_CLIENT_ID" == "$expected_reversed_client_id" ]] || fail "GOOGLE_SIGN_IN_IOS_REVERSED_CLIENT_ID must match GOOGLE_SIGN_IN_IOS_CLIENT_ID"

config_file="ios/Flutter/GoogleSignIn.xcconfig"
config_directory="$(dirname "$config_file")"
temporary_config_file="$(mktemp "$config_directory/.GoogleSignIn.xcconfig.XXXXXX")"
trap 'rm -f "$temporary_config_file"' EXIT

umask 077
{
  printf '%s\n' '// Generated by scripts/prepare_ios_google_sign_in_config.sh. Do not commit.'
  printf 'GOOGLE_SIGN_IN_IOS_CLIENT_ID = %s\n' "$GOOGLE_SIGN_IN_IOS_CLIENT_ID"
  printf 'GOOGLE_SIGN_IN_IOS_REVERSED_CLIENT_ID = %s\n' "$GOOGLE_SIGN_IN_IOS_REVERSED_CLIENT_ID"
  printf 'GOOGLE_SIGN_IN_SERVER_CLIENT_ID = %s\n' "$GOOGLE_SIGN_IN_SERVER_CLIENT_ID"
} > "$temporary_config_file"

mv -f "$temporary_config_file" "$config_file"
trap - EXIT

printf '%s\n' 'Prepared ios/Flutter/GoogleSignIn.xcconfig from environment variables.'
